#!/bin/bash
############################################################
# Starter
############################################################
echo "Installing APT and APT-GET proxy"
echo '' > /etc/apt/apt.conf.d/30proxy
echo 'Acquire::http { Proxy "http://192.168.88.100:3142"; }' > /etc/apt/apt.conf.d/proxy

mkdir -p /mnt/storage_share

add-apt-repository ppa:inkscape.dev/stable


apt upgrade -y
apt update -y
############################################################
# Python3
############################################################
echo "Installing Python"
apt install -y \
    python3 \
    python3-venv \
    python3-pip \
    python3-dev \
    python3-wheel \
    python3-gevent \
    python-is-python3 \
    python3-ldap \
    python3-ldap3 \
    python3-pyldap \
    libldap2-dev \
    libsasl2-dev \
    pre-commit
    


echo "Configure pip proxy"
echo << EOF
[global]
index-url=http://192.168.88.100:5000/index/
extra-index-url=http://pypi.python.org/pypi

[install]
trusted-host=192.168.88.100
	     pypi.python.org
EOF
> /etc/pip.conf


############################################################
# Cockpit
############################################################
echo "Installing cockpit"
. /etc/os-release
apt install -y -t ${VERSION_CODENAME}-backports \
    cockpit \
    cockpit-pcp \
    cockpit-bridge \
    cockpit-storaged \
    nfs-common \
    openssh-server \
    openssh-client


systemctl enable cockpit


############################################################
# Developer Tools
############################################################
   snap install code --classic
snap install postman
snap install chromium
snap install skype
snap install audacity
apt install -y \
    git \
    inkscape \
    build-essential \
    default-jdk \
    libpq-dev

snap install node --classic
npm install -g rtlcss

apt install -y \
    vlc \
    vlc-plugin-base \
    vlc-plugin-access-extra \
    vlc-plugin-bittorrent \
    vlc-plugin-video-splitter

############################################################
# Docker
############################################################
apt install -y \
    docker \
    docker-compose \
    docker-compose-v2

systemctl enable docker



############################################################
# Cokpit
############################################################
mkdir -p /root/.ssh
touch /root/.ssh/authorized_keys
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgkKnDH/\
ruQAquOB1FgQW0glN7vVnTJnNoiESNbrgPI46od4dwVoR+Xc4wVU\
qP3eRhbOCgqlilxdos6XgG8y7fuDgA3MVEIyvO3pUF3jRhTw7uJm\
3JOMFyfxBAszlQsOROU24HdaUEAWNi4z1Ks6P+oTywa76A0NbHGU\
kydDnCirEVtP+lSR715s3GP0E5SKrlIYoSiI0v4EFItWdU8oIYr9\
pa7s0G1tm1XZ8CLHTGUZKxeo8bQRYEbn8DtRReL5R5val3DBWxdj\
ybRuQGnT05xvn687AjeOdrC8p95bLlaV+/H+C5umHYmKottlPYGd\
YUoZVXWgM4WAJ2GLUYMcFdZRiCvzChocp8e3PGbsdquyESsEvMAq\
j9KFfDAejiV3i32IN4eJcOp3uW3Fx9nI+fbSit0qWwoS4RSz440L\
5+PNZ+AdAXs9/7wxkMjXWkr8naJXbg1oTG3M8XtjMZkfpYRuJ2P5\
2/fXpSXIrSHkPjUXc9j8i+vj+VFE+QJxhxB/E= \
maso@localhost.localdomain" >> "/root/.ssh/authorized_keys"
