
ERROR_CODE_PRE_VERIFICATION = 19841
ERROR_CODE_POST_VERIFICATION = 19842


RESOURCE_PREFIX_VIRTUAL = 'virtual://'
RESOURCE_PREFIX_APPLICATION = 'app://'

RESOURCE_PRIORITY_DEFAULT = 10
RESOURCE_PRIORITY_ROOT = 1000
RESOURCE_PRIORITY_EXTEND = 9
